--liquibase formatted sql

--changeset mihail:2022-01-06--02-create-users-table
CREATE TABLE USERS(ID BIGINT AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(15),
PASSWORD VARCHAR(30),
EMAIL VARCHAR(100));