--liquibase formatted sql

--changeset mihail:2022-01-07--05-create-comments-table
CREATE TABLE COMMENTS(ID SERIAL UNIQUE ,
MESSAGE VARCHAR(250),
DATE_MESSAGE TIMESTAMP,
ID_USER BIGINT,
ID_POST BIGINT,
FOREIGN KEY (ID_USER) REFERENCES USERS(ID),
FOREIGN KEY (ID_POST) REFERENCES POSTS(ID) ON DELETE CASCADE);