#
#spring.datasource.url=jdbc:mysql://localhost:3306/instazoo?useSSL=false&serverTimezone=UTC
#spring.datasource.username=superuser
#spring.datasource.password=superuser

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_blog?useSSL=false&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver
    username: superuser
    password: superuser
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

logging:
  level:
    root: ERROR